"""which recived comments are new

Revision ID: 0c3534307aa3
Revises: 8a3a3e44270d
Create Date: 2019-07-08 09:00:00.777408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3534307aa3'
down_revision = '8a3a3e44270d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_recived_comments_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_recived_comments_read_time')

    # ### end Alembic commands ###
